#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci delete system.ntp.server
uci add_list system.ntp.server='ntp.tencent.com'
uci add_list system.ntp.server='ntp1.aliyun.com'
uci add_list system.ntp.server='ntp.ntsc.ac.cn'
uci add_list system.ntp.server='cn.ntp.org.cn'
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0
