#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: 打包晶晨固件
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      REPO_URL:
        description: '请输入您要编译的源码仓库'
        required: true
        default: 'coolsnowwolf/lede'
      REPO_BRANCH:
        description: '请输入源码的分支'
        required: true
        default: 'master'
      CONFIG_FILE:
        description: '输入set_config文件夹里面的配置文件名称'
        required: true
        default: 'x86_64'
      UPLOAD_FIRMWARE:
        description: '上传固件到 Github Artifacts'
        required: false
        default: 'true'
        type: boolean
      UPLOAD_RELEASE:
        description: '发布固件到 Github Releases'
        required: false
        default: 'true'
        type: boolean
      days:
        description: '清理[X]天之前的Actions空间操作记录(可改)'
        required: true
        default: '7'
      rele:
        description: '保留[X]个Releases不被删除(可改)'
        required: true
        default: '10'
        
env:
  DIY_SOURCE: diy
  DIY_FILES: files
  DIY_PATCH: patches
  DIY_PART_SH: diy-part.sh
  FEEDS_CONF: feeds.conf.default
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
    name: ${{ inputs.REPO_URL }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: 部署编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /usr/lib/jvm /opt/ghc /swapfile
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'
        sudo -E apt-get -qq install -y rename pigz libfuse-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: 拉取源码
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone https://github.com/${{ inputs.REPO_URL }} -b ${{ inputs.REPO_BRANCH }} openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        echo "HOME_PATH=$GITHUB_WORKSPACE/openwrt" >> $GITHUB_ENV

    - name: 读取自定义文件
      run: |
        cd openwrt
        ./scripts/feeds update -a > /dev/null 2>&1
        [[ -f "$GITHUB_WORKSPACE/${{ inputs.FEEDS_CONF }}" ]] && mv -f $GITHUB_WORKSPACE/${{ inputs.FEEDS_CONF }} feeds.conf.default
        [[ -d "$GITHUB_WORKSPACE/${{ env.DIY_SOURCE }}" ]] && cp -Rf $GITHUB_WORKSPACE/${{ env.DIY_SOURCE }}/* $GITHUB_WORKSPACE/openwrt/
        [[ -d "$GITHUB_WORKSPACE/${{ env.DIY_FILES }}" ]] && mv -f $GITHUB_WORKSPACE/${{ env.DIY_FILES }}/* files
        [[ -d "$GITHUB_WORKSPACE/${{ env.DIY_PACTH }}" ]] && \
        find "$GITHUB_WORKSPACE/${{ env.DIY_PACTH }}" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 --forward --no-backup-if-mismatch"
        [[ -f "$GITHUB_WORKSPACE/set_config/${{ inputs.CONFIG_FILE }}" ]] && cp -Rf $GITHUB_WORKSPACE/set_config/${{ inputs.CONFIG_FILE }} ${HOME_PATH}/.config
        echo "CONFIG_PACKAGE_luci=y" >> ${HOME_PATH}/.config
        chmod +x $GITHUB_WORKSPACE/${{ inputs.DIY_PART_SH }}
        $GITHUB_WORKSPACE/${{ inputs.DIY_PART_SH }}

    - name: 安装源码插件源
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a > /dev/null 2>&1
        ./scripts/feeds install -a

    - name: 下载软件源
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: 开始编译固件
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s

        export TARGET_BOARD="$(awk -F '[="]+' '/TARGET_BOARD/{print $2}' ${HOME_PATH}/.config)"
        export TARGET_SUBTARGET="$(awk -F '[="]+' '/TARGET_SUBTARGET/{print $2}' ${HOME_PATH}/.config)"
        export TARGET_PROFILE_DG="$(awk -F '[="]+' '/TARGET_PROFILE/{print $2}' ${HOME_PATH}/.config)"
        if [[ `grep -Eoc 'CONFIG_TARGET_x86_64=y' ${HOME_PATH}/.config` -eq '1' ]]; then
          echo "TARGET_PROFILE=x86-64" >> $GITHUB_ENV
        elif [[ `grep -Eoc 'CONFIG_TARGET_x86=y' ${HOME_PATH}/.config` -eq '1' ]]; then
          echo "TARGET_PROFILE=x86-32" >> $GITHUB_ENV
        elif [[ `grep -Eoc 'CONFIG_TARGET_armvirt_64_Default=y' ${HOME_PATH}/.config` -eq '1' ]]; then
          echo "TARGET_PROFILE=Armvirt_64" >> $GITHUB_ENV
        elif [[ `grep -Eoc "CONFIG_TARGET.*DEVICE.*=y" ${HOME_PATH}/.config` -eq '1' ]]; then
          echo "TARGET_PROFILE=$(grep -Eo "CONFIG_TARGET.*DEVICE.*=y" ${HOME_PATH}/.config | sed -r 's/.*DEVICE_(.*)=y/\1/')" >> $GITHUB_ENV
        else
          echo "TARGET_PROFILE=${TARGET_PROFILE_DG}" >> $GITHUB_ENV
        fi
        echo "FIRMWARE_PATH=${HOME_PATH}/bin/targets/${TARGET_BOARD}/${TARGET_SUBTARGET}" >> $GITHUB_ENV
        echo "FILE_DATE=-$(date +"%Y.%m%d.%H%M")" >> $GITHUB_ENV
        echo "date=$(date +'%m.%d')" >> $GITHUB_ENV

    - name: 上传固件至actions
      uses: actions/upload-artifact@main
      if: steps.compile.outcome == 'success'&& github.event.inputs.UPLOAD_FIRMWARE == 'true' && !cancelled()
      with:
        name: ${{ env.TARGET_PROFILE }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE_PATH }}

    - name: 发布固件到release
      if: steps.tag.outcome == 'success' && github.event.inputs.UPLOAD_RELEASE == 'true' && env.REPO_TOKEN
      uses: ncipollo/release-action@main
      with:
        name: ${{ env.TARGET_PROFILE }}
        tag: ${{ env.FILE_DATE }}
        token: ${{ secrets.REPO_TOKEN }}
        allowUpdates: true
        artifacts: "${{ env.FIRMWARE_PATH }}/*"

    - name: 清理Actions空间
      if: env.REPO_TOKEN
      uses: Mattraks/delete-workflow-runs@v2
      with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: ${{ inputs.days }}
          keep_minimum_runs: 0
    
    - name: 删除releases
      if: env.REPO_TOKEN
      uses: danshui-git/delete-older-releases@main
      with:
        repo: ${{ github.repository }}
        keep_latest: ${{ inputs.rele }}
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
