#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: 编译固件
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      REPO_URL:
        description: '请输入您要编译的源码仓库'
        required: true
        default: 'coolsnowwolf/lede'
      REPO_BRANCH:
        description: '请输入源码的分支'
        required: true
        default: 'master'
      CONFIG_FILE:
        description: '请输入set_config文件夹里的配置文件名称'
        required: true
        default: 'x86_64'
      DIY_PART_SH:
        description: '请选择LUCI版本的自定义文件'
        required: true
        default: '1806-luci.sh'
        type: choice
        options:
          - '1806-luci.sh'
          - '1907-luci.sh'
      days:
        description: '清理[X]天之前的Artifacts'
        required: true
        default: '7'
      rele:
        description: '保留[X]个Releases不被删除'
        required: true
        default: '10'
      UPLOAD_FIRMWARE:
        description: '上传固件到 Artifacts'
        required: false
        default: 'true'
        type: boolean
      UPLOAD_RELEASE:
        description: '发布固件到 Releases'
        required: false
        default: 'false'
        type: boolean
      CACHEWRTBUILD_SWITCH:
        description: '缓存加速编译'
        required: false
        default: 'true'
        type: boolean
        
# 定时触发开启开始编译(把下面两个#去掉开启)
#  schedule:
#   - cron: 35 4 * * *
        
env:
  REPO_URL: coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: x86_64
  DIY_PART_SH: 1806-luci.sh
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: false
  CACHEWRTBUILD_SWITCH: true
  # 定时编译的话，控制于以上为准
  DIY_SOURCE: diy
  DIY_FILES: files
  DIY_PATCH: patches
  FEEDS_CONF: feeds.conf.default
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
    name: 编译固件

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: 读取变量
      run: |
        export SOURCE="$(echo "${{ inputs.REPO_URL }}" |cut -d"/" -f1)"
        export LUCI_VERSION="$(echo "${{ inputs.REPO_BRANCH }}" |cut -d"-" -f2-)"
        export DIY_WORK="${SOURCE}$(echo "${LUCI_VERSION}" |tr -d '\`.`')"
        echo "SOURCE=${SOURCE}" >> $GITHUB_ENV
        echo "LUCI_VERSION=${LUCI_VERSION}" >> $GITHUB_ENV
        echo "DIY_WORK=${DIY_WORK}" >> $GITHUB_ENV
        if [[ -n "${{ inputs.REPO_URL }}" ]]; then
          echo "REPO_URL=https://github.com/${{ inputs.REPO_URL }}" >> ${GITHUB_ENV}
          echo "REPO_BRANCH=${{ inputs.REPO_BRANCH }}" >> ${GITHUB_ENV}
          echo "CONFIG_FILE=${{ inputs.CONFIG_FILE }}" >> ${GITHUB_ENV}
          echo "DIY_PART_SH=${{ inputs.DIY_PART_SH }}" >> ${GITHUB_ENV}
          echo "UPLOAD_FIRMWARE=${{ inputs.UPLOAD_FIRMWARE }}" >> ${GITHUB_ENV}
          echo "UPLOAD_RELEASE=${{ inputs.UPLOAD_RELEASE }}" >> ${GITHUB_ENV}
          echo "CACHEWRTBUILD_SWITCH=${{ inputs.CACHEWRTBUILD_SWITCH }}" >> ${GITHUB_ENV}
        else
          echo "REPO_URL=https://github.com/${REPO_URL}" >> ${GITHUB_ENV}
          echo "REPO_BRANCH=${REPO_BRANCH}" >> ${GITHUB_ENV}
          echo "CONFIG_FILE=${CONFIG_FILE}" >> ${GITHUB_ENV}
          echo "DIY_PART_SH=${DIY_PART_SH}" >> ${GITHUB_ENV}
          echo "UPLOAD_FIRMWARE=${UPLOAD_FIRMWARE}" >> ${GITHUB_ENV}
          echo "UPLOAD_RELEASE=${UPLOAD_RELEASE}" >> ${GITHUB_ENV}
          echo "CACHEWRTBUILD_SWITCH=${CACHEWRTBUILD_SWITCH}" >> ${GITHUB_ENV}
        fi

    - name: 部署编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /usr/lib/jvm /opt/ghc /swapfile
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'
        sudo -E apt-get -qq install -y rename pigz libfuse-dev
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /${{ env.DIY_WORK }}
        sudo chown $USER:$GROUPS /${{ env.DIY_WORK }}

    - name: 拉取源码
      working-directory: /${{ env.DIY_WORK }}
      run: |
        df -hT $PWD
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /${{ env.DIY_WORK }}/openwrt $GITHUB_WORKSPACE/openwrt
        echo "HOME_PATH=$GITHUB_WORKSPACE/openwrt" >> $GITHUB_ENV
        echo "ZZZ_PATH=$(find "$GITHUB_WORKSPACE/openwrt/package" -type f -name "*-default-settings")" >> $GITHUB_ENV
        export GENERATE_PATH="${GITHUB_WORKSPACE}/openwrt/package/base-files/files/bin/config_generate"
        echo "GENERATE_PATH=${GENERATE_PATH}" >> $GITHUB_ENV
        echo "IPADDR=$(grep "ipaddr:-" "${GENERATE_PATH}" |grep -v 'addr_offset' |grep -Eo "[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+")" >> $GITHUB_ENV

    - name: 读取扩展文件
      run: |
        cd openwrt
        ./scripts/feeds update -a > /dev/null 2>&1
        [[ -f "$GITHUB_WORKSPACE/${{ env.FEEDS_CONF }}" ]] && mv -f $GITHUB_WORKSPACE/${{ env.FEEDS_CONF }} feeds.conf.default
        [[ -d "$GITHUB_WORKSPACE/${{ env.DIY_SOURCE }}" ]] && cp -Rf $GITHUB_WORKSPACE/${{ env.DIY_SOURCE }}/* $GITHUB_WORKSPACE/openwrt/
        [[ -d "$GITHUB_WORKSPACE/${{ env.DIY_FILES }}" ]] && mv -f $GITHUB_WORKSPACE/${{ env.DIY_FILES }}/* files
        [[ -d "$GITHUB_WORKSPACE/${{ env.DIY_PACTH }}" ]] && \
        find "$GITHUB_WORKSPACE/${{ env.DIY_PACTH }}" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 --forward --no-backup-if-mismatch"
        chmod +x $GITHUB_WORKSPACE/${{ inputs.DIY_PART_SH }}
        $GITHUB_WORKSPACE/${{ inputs.DIY_PART_SH }}

    - name: 安装源码插件源
      run: |
        cd openwrt
        if [[ "${{ inputs.DIY_PART_SH }}" == "1907-luci.sh" ]]; then
          wget -q https://raw.githubusercontent.com/281677160/common-main/main/language/zh_Hans.sh -O ${HOME_PATH}/zh_Hans.sh
          sudo chmod +x ${HOME_PATH}/zh_Hans.sh
          /bin/bash ${HOME_PATH}/zh_Hans.sh
          rm -rf ${HOME_PATH}/zh_Hans.sh
        fi
        ./scripts/feeds update -a
        ./scripts/feeds install -a > /dev/null 2>&1
        ./scripts/feeds install -a
        [[ -f "$GITHUB_WORKSPACE/set_config/${{ inputs.CONFIG_FILE }}" ]] && \
        cp -Rf $GITHUB_WORKSPACE/set_config/${{ inputs.CONFIG_FILE }} ${HOME_PATH}/.config
        echo "CONFIG_PACKAGE_luci=y" >> ${HOME_PATH}/.config

    - name: 下载软件源
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        export TARGET_BOARD="$(awk -F '[="]+' '/TARGET_BOARD/{print $2}' ${HOME_PATH}/.config)"
        export TARGET_SUBTARGET="$(awk -F '[="]+' '/TARGET_SUBTARGET/{print $2}' ${HOME_PATH}/.config)"
        export TARGET_PROFILE_DG="$(awk -F '[="]+' '/TARGET_PROFILE/{print $2}' ${HOME_PATH}/.config)"
        echo "FIRMWARE_PATH=${HOME_PATH}/bin/targets/${TARGET_BOARD}/${TARGET_SUBTARGET}" >> $GITHUB_ENV
        if [[ `grep -c 'CONFIG_TARGET_x86_64=y' ${HOME_PATH}/.config` -eq '1' ]]; then
          echo "TARGET_PROFILE=x86-64" >> $GITHUB_ENV
        elif [[ `grep -c 'CONFIG_TARGET_x86=y' ${HOME_PATH}/.config` -eq '1' ]]; then
          echo "TARGET_PROFILE=x86-32" >> $GITHUB_ENV
        elif [[ `grep -c 'CONFIG_TARGET_armvirt_64_Default=y' ${HOME_PATH}/.config` -eq '1' ]]; then
          echo "TARGET_PROFILE=Armvirt_64" >> $GITHUB_ENV
        elif [[ `grep -c "CONFIG_TARGET.*DEVICE.*=y" ${HOME_PATH}/.config` -eq '1' ]]; then
          echo "TARGET_PROFILE=$(grep -Eo "CONFIG_TARGET.*DEVICE.*=y" ${HOME_PATH}/.config | sed -r 's/.*DEVICE_(.*)=y/\1/')" >> $GITHUB_ENV
        else
          echo "TARGET_PROFILE=${TARGET_PROFILE_DG}" >> $GITHUB_ENV
        fi
        
    - name: 缓存加速
      if: github.event.inputs.CACHEWRTBUILD_SWITCH == 'true'
      uses: stupidloud/cachewrtbuild@main
      with:
        ccache: 'true'
        mixkey: "${{ env.TARGET_PROFILE }}"
        prefix: ${{ github.workspace }}/openwrt

    - name: 开始编译固件
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        echo "FILE_DATE=$(date +"%Y.%m%d.%H%M")" >> $GITHUB_ENV
        echo "date=$(date +'%m.%d')" >> $GITHUB_ENV
        cd "${FIRMWARE_PATH}"
        mkdir -p ipk
        cp -rf $(find ${HOME_PATH}/bin/packages/ -type f -name "*.ipk") ipk/ && sync
        sudo tar -czf ipk.tar.gz ipk && sync
        sudo rm -rf ipk profiles.json packages

    - name: 上传固件至Artifacts
      if: steps.compile.outcome == 'success'&& github.event.inputs.UPLOAD_FIRMWARE == 'true' && !cancelled()
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.SOURCE }}-${{ env.LUCI_VERSION }}-${{ env.TARGET_PROFILE }}-${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE_PATH }}

    - name: 发布固件到release
      if: steps.compile.outcome == 'success' && github.event.inputs.UPLOAD_RELEASE == 'true' && env.REPO_TOKEN
      uses: ncipollo/release-action@main
      with:
        name: ${{ env.SOURCE }}-${{ env.LUCI_VERSION }}-${{ env.TARGET_PROFILE }}
        tag: ${{ env.FILE_DATE }}
        token: ${{ secrets.REPO_TOKEN }}
        allowUpdates: true
        artifacts: "${{ env.FIRMWARE_PATH }}/*"

    - name: 清理Artifacts
      if: env.REPO_TOKEN
      uses: Mattraks/delete-workflow-runs@v2
      with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: ${{ inputs.days }}
          keep_minimum_runs: 0
    
    - name: 删除releases
      if: env.REPO_TOKEN
      uses: danshui-git/delete-older-releases@main
      with:
        repo: ${{ github.repository }}
        keep_latest: ${{ inputs.rele }}
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
