
name: Use Releases file to Packaging

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      source_branch:
        description: '请输入源码仓库,比如：coolsnowwolf/lede'
        required: true
        default: ''
      amlogic_model:
        description: '请输入机型,比如：s905d 或 s905d_s905x2'
        required: true
        default: ''
      amlogic_kernel:
        description: '请输入内核,比如：5.10.172 或 5.15.97_6.1.16'
        required: true
        default: ''
      auto_kernel:
        description: "是否自动检测最新内核"
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      rootfs_size:
        description: '设置rootfs大小(单位：MiB),比如：960'
        required: true
        default: '1024'
      kernel_repo:
        description: "内核仓库地址"
        required: false
        default: 'https://github.com/ophub/kernel/tree/main/pub'
        
  push:
    branches:
      - main
    paths:
      - 'relevance/start'

env:
  GIT_REPOSITORY: ${{github.repository}}
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  SOURCE: immortalwrt

jobs:
  build:
    name: Build OpenWrt firmware
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:    
    - name: Checkout
      uses: actions/checkout@v3

    - name: 相关变量
      run: |
        cd ${GITHUB_WORKSPACE}
        if [[ -n "${{ github.event.inputs.openwrt_board }}" ]]; then
          echo "SOURCE="$(echo "${{ inputs.source_branch }}" |cut -d"/" -f1)"" >> ${GITHUB_ENV}
          echo "amlogic_model=${{ inputs.amlogic_model }}" >> ${GITHUB_ENV}
          echo "amlogic_kernel=${{ inputs.amlogic_kernel }}" >> ${GITHUB_ENV}
          echo "auto_kernel=${{ inputs.auto_kernel }}" >> ${GITHUB_ENV}
          echo "kernel_repo=${{ inputs.kernel_repo }}" >> ${GITHUB_ENV}
          echo "rootfs_size=${{ inputs.rootfs_size }}" >> ${GITHUB_ENV}
        else
          source relevance/start.ini
          echo "SOURCE=${SOURCE}" >> ${GITHUB_ENV}
          echo "amlogic_model=${amlogic_model}" >> ${GITHUB_ENV}
          echo "amlogic_kernel=${amlogic_kernel}" >> ${GITHUB_ENV}
          echo "auto_kernel=${auto_kernel}" >> ${GITHUB_ENV}
          echo "kernel_repo=${kernel_repo}" >> ${GITHUB_ENV}
          echo "rootfs_size=${rootfs_size}" >> ${GITHUB_ENV}
        fi
      
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /usr/lib/jvm /opt/ghc /swapfile
        sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'
        sudo -E apt-get -y install $(curl -fsSL https://is.gd/depend_ubuntu2204_openwrt)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
    
    - name: 在releases下载 rootfs.tar.gz 压缩包
      working-directory: /workdir
      run: |
        df -hT $PWD
        mkdir -p openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        
        echo "build_tag=OpenWrt_${{ env.SOURCE }}_$(date +"%m.%d.%H%M")" >> ${GITHUB_ENV}
        wget -q https://github.com/${{ env.GIT_REPOSITORY }}/releases/download/targz/${{ env.SOURCE }}-armvirt-64-default-rootfs.tar.gz -O openwrt/openwrt-armvirt-64-default-rootfs.tar.gz
    
    - name: Build OpenWrt firmware
      uses: ophub/amlogic-s9xxx-openwrt@main
      with:
        openwrt_path: openwrt/*rootfs.tar.gz
        openwrt_board: ${{ env.amlogic_model }}
        openwrt_kernel: ${{ env.amlogic_kernel }}
        auto_kernel: ${{ env.auto_kernel }}
        kernel_repo: ${{ env.kernel_repo }}
        openwrt_size: ${{ env.rootfs_size }}
        gh_token: ${{ secrets.REPO_TOKEN }}
        
    - name: Upload the packaged firmware to Release
      uses: ncipollo/release-action@main
      with:
        name: ${{ env.build_tag }}
        tag: ${{ env.SOURCE }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        allowUpdates: true
        removeArtifacts: true
        token: ${{ secrets.REPO_TOKEN }}
        body: |
          This is OpenWrt firmware for Amlogic and Rockchip
          * Firmware information
          Install to EMMC: Login to OpenWrt → System → Amlogic Service → Install OpenWrt
