
name: Use Releases file to Packaging

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      source_branch:
        description: 'Select the source branch'
        required: true
        default: 'lede'
      openwrt_board:
        description: "Select device board"
        required: true
        default: 'all'
      openwrt_kernel:
        description: "Select kernel version"
        required: true
        default: '5.15.85_6.1.1'
      auto_kernel:
        description: "Auto use the latest kernel"
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      openwrt_size:
        description: "Set the rootfs size(Unit: MiB)"
        required: true
        default: '1024'
      kernel_repo:
        description: "Set the kernel repository"
        required: false
        default: 'https://github.com/ophub/kernel/tree/main/pub'
      
      
      # 这个可以搞简单点的，勾选默认就是你仓库就行了，在下载那里做个判断
      other_warehouses:
        description: '若勾选则用别人仓库的rootfs.tar.gz包'
        required: false
        default: 'false'
        type: boolean
      storehouse_name:
        description: "别人仓库 帐号/仓库"
        required: true
        default: 'ophub/amlogic-s9xxx-openwrt'
      storehouse_tags:
        description: "别人仓库Releases的tags"
        required: true
        default: 'OpenWrt_lede_03.11.2204'
      targz_name:
        description: "别人仓库Releases上的rootfs.tar.gz包全名称"
        required: true
        default: 'openwrt-armvirt-64-default-rootfs.tar.gz'
        
  push:
    branches:
      - main
    paths:
      - 'trigger-program/ledestart'

env:
  GIT_REPOSITORY: ${{github.repository}}
  TZ: America/New_York
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  SOURCE: lede                             # 这个不用管的，自动触发的时候会自动修改，手动启动就是用source_branch

jobs:
  build:
    name: Build OpenWrt firmware
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:    
    - name: Checkout
      uses: actions/checkout@v3

    - name: 相关变量
      run: |
        cd ${GITHUB_WORKSPACE}
        if [[ -n "${{ github.event.inputs.openwrt_board }}" ]]; then
          # 手动启动就用这个变量
          echo "SOURCE=${{ inputs.source_branch }}" >> ${GITHUB_ENV}
          echo "openwrt_board=${{ inputs.openwrt_board }}" >> ${GITHUB_ENV}
          echo "openwrt_kernel=${{ inputs.openwrt_kernel }}" >> ${GITHUB_ENV}
          echo "auto_kernel=${{ inputs.auto_kernel }}" >> ${GITHUB_ENV}
          echo "kernel_repo=${{ inputs.kernel_repo }}" >> ${GITHUB_ENV}
          echo "openwrt_size=${{ inputs.openwrt_size }}" >> ${GITHUB_ENV}
        else
          # 触发启动就是trigger-program文件夹的对应${{ env.SOURCE }}.ini
          source trigger-program/${{ env.SOURCE }}.ini
          echo "SOURCE=${SOURCE}" >> ${GITHUB_ENV}
          echo "openwrt_board=${openwrt_board}" >> ${GITHUB_ENV}
          echo "openwrt_kernel=${openwrt_kernel}" >> ${GITHUB_ENV}
          echo "auto_kernel=${auto_kernel}" >> ${GITHUB_ENV}
          echo "kernel_repo=${kernel_repo}" >> ${GITHUB_ENV}
          echo "openwrt_size=${openwrt_size}" >> ${GITHUB_ENV}
        fi
      
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        source trigger-program/packaging_program.sh && Build_environment
        echo "status=success" >> ${GITHUB_OUTPUT}
    
    - name: 在releases下载 rootfs.tar.gz 压缩包
      working-directory: /workdir
      run: |
        df -hT $PWD
        mkdir -p openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        
        # 下载之前，应该要搞个API来验证一下仓库有没有该default-rootfs.tar.gz包
        
        if [[ "${{ inputs.other_warehouses }}" == "true" ]]; then
          # 用其他仓库就这个链接下载
          echo "build_tag=OpenWrt_other_$(date +"%m.%d.%H%M")" >> ${GITHUB_ENV}
          echo "SOURCE=other" >> ${GITHUB_ENV}
          wget -q https://github.com/${{ inputs.storehouse_name }}/releases/download/${{ inputs.storehouse_tags }}/${{ inputs.targz_name }} -O openwrt/openwrt-armvirt-64-default-rootfs.tar.gz
        else
          # 自身仓库就这个
          echo "build_tag=OpenWrt_${{ env.SOURCE }}_$(date +"%m.%d.%H%M")" >> ${GITHUB_ENV}
          wget -q https://github.com/${{ env.GIT_REPOSITORY }}/releases/download/targz/${{ env.SOURCE }}-armvirt-64-default-rootfs.tar.gz -O openwrt/openwrt-armvirt-64-default-rootfs.tar.gz
        fi
    
    - name: Build OpenWrt firmware
      uses: ophub/amlogic-s9xxx-openwrt@main
      with:
        openwrt_path: openwrt/*rootfs.tar.gz
        openwrt_board: ${{ env.openwrt_board }}
        openwrt_kernel: ${{ env.openwrt_kernel }}
        auto_kernel: ${{ env.auto_kernel }}
        kernel_repo: ${{ env.kernel_repo }}
        openwrt_size: ${{ env.openwrt_size }}
        gh_token: ${{ secrets.GH_TOKEN }}
        
    - name: Upload the packaged firmware to Release
      uses: ncipollo/release-action@main
      with:
        name: ${{ env.build_tag }}
        tag: ${{ env.SOURCE }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        allowUpdates: true
        removeArtifacts: true
        token: ${{ secrets.GH_TOKEN }}
        body: |
          This is OpenWrt firmware for Amlogic and Rockchip
          * Firmware information
          Default IP: 192.168.1.1
          Default username: root
          Default password: password
          Default WIFI name: OpenWrt
          Default WIFI password: none
          Install to EMMC: Login to OpenWrt → System → Amlogic Service → Install OpenWrt
